import { createStepContext } from '../../../test';
import { Recording, setupRecording } from '@jupiterone/integration-sdk-testing';
import step from '../fetchUsers';

let recording: Recording;

afterEach(async () => {
  await recording.stop();
});

test('should fetch users in account', async () => {
  recording = setupRecording({
    name: 'users',
    directory: __dirname,
  });

  const context = createStepContext();
  await step.executionHandler(context);
  const entities = context.jobState.collectedEntities;

  expect(entities).toHaveLength(5);
  expect(entities).toEqual(
    expect.arrayContaining([
      expect.objectContaining({
        email: 'adam.pierson@jupiterone.com',
        status: 'active',
        username: 'adam.pierson@jupiterone.com',
        _type: 'duo_admin',
        _class: ['User'],
        name: 'Adam Pierson',
        displayName: 'Adam Pierson',
        active: true,
      }),
      expect.objectContaining({
        email: 'austin.kelleher+duotest@jupiterone.com',
        status: 'active',
        username: 'austinkellehertest',
        _type: 'duo_user',
        _class: ['User'],
        name: 'Austin Kelleher Test',
        displayName: 'Austin Kelleher Test',
        active: true,
      }),
    ]),
  );
});

[
  {
    _class: ['Account'],
    _key: 'duo-account:56cd46b9:jupiterone-inc',
    _rawData: [
      {
        name: 'default',
        rawData: {
          enrollment_module: 'new',
          fraud_email: '',
          fraud_email_enabled: true,
          helpdesk_bypass: 'allow',
          helpdesk_bypass_expiration: 0,
          helpdesk_can_send_enroll_email: false,
          helpdesk_message: '',
          inactive_admin_expiration: 0,
          inactive_user_expiration: 0,
          instant_restore_enabled: 1,
          language: 'EN',
          lockout_expire_duration: null,
          lockout_threshold: 10,
          log_retention_days: null,
          minimum_password_length: 12,
          mobile_analytics_disabled: 0,
          mobile_otp_enabled: false,
          name: 'JupiterOne Inc',
          password_requires_lower_alpha: false,
          password_requires_numeric: false,
          password_requires_special: false,
          password_requires_upper_alpha: false,
          push_enabled: false,
          reactivation_integration_key: null,
          reactivation_url: '',
          req_fips_passcodes_android: false,
          security_checkup_enabled: 1,
          sms_batch: 1,
          sms_enabled: false,
          sms_expiration: 0,
          sms_message: 'SMS passcodes',
          sms_refresh: 0,
          telephony_warning_min: 0,
          timezone: 'UTC',
          user_telephony_cost_max: 20,
        },
      },
    ],
    _type: 'duo_account',
    createdOn: undefined,
    displayName: 'JupiterOne Inc Duo Account',
    enrollmentModule: 'new',
    fraudEmail: '',
    fraudEmailEnabled: true,
    helpdeskBypass: 'allow',
    helpdeskBypassExpiration: 0,
    helpdeskCanSendEnrollEmail: false,
    helpdeskMessage: '',
    inactiveAdminExpiration: 0,
    inactiveUserExpiration: 0,
    instantRestoreEnabled: 1,
    language: 'EN',
    lockoutThreshold: 10,
    minimumPasswordLength: 12,
    mobileAnalyticsDisabled: 0,
    mobileOtpEnabled: false,
    name: 'JupiterOne Inc',
    passwordRequiresLowerAlpha: false,
    passwordRequiresNumeric: false,
    passwordRequiresSpecial: false,
    passwordRequiresUpperAlpha: false,
    pushEnabled: false,
    reactivationUrl: '',
    reqFipsPasscodesAndroid: false,
    securityCheckupEnabled: 1,
    siteId: '56cd46b9',
    smsBatch: 1,
    smsEnabled: false,
    smsExpiration: 0,
    smsMessage: 'SMS passcodes',
    smsRefresh: 0,
    telephonyWarningMin: 0,
    timezone: 'UTC',
    userTelephonyCostMax: 20,
    webLink: 'https://admin-56cd46b9.duosecurity.com/',
  },
  {
    _class: ['User'],
    _key: 'duo-admin:DE5L076HW5D9M0LSGS35',
    _rawData: [
      {
        name: 'default',
        rawData: {
          admin_id: 'DE5L076HW5D9M0LSGS35',
          admin_units: [],
          email: 'austin.kelleher@jupiterone.dev',
          hardtoken: null,
          last_login: 1645116159,
          name: 'Austin Kelleher',
          password_change_required: false,
          phone: '+15859430080',
          restricted_by_admin_units: false,
          role: 'Owner',
          status: 'Active',
        },
      },
    ],
    _type: 'duo_admin',
    active: true,
    admin: true,
    adminId: 'DE5L076HW5D9M0LSGS35',
    createdOn: undefined,
    displayName: 'Austin Kelleher',
    email: 'austin.kelleher@jupiterone.dev',
    id: 'DE5L076HW5D9M0LSGS35',
    lastLogin: 1645116159,
    name: 'Austin Kelleher',
    passwordChangeRequired: false,
    phone: '+15859430080',
    restrictedByAdminUnits: false,
    role: 'Owner',
    status: 'active',
    username: 'austin.kelleher@jupiterone.dev',
  },
  {
    _class: ['User'],
    _key: 'duo-admin:DEUDTXS9EB88IQN84PY5',
    _rawData: [
      {
        name: 'default',
        rawData: {
          admin_id: 'DEUDTXS9EB88IQN84PY5',
          admin_units: [],
          email: 'adam.pierson@jupiterone.com',
          hardtoken: null,
          last_login: 1645136145,
          name: 'Adam Pierson',
          password_change_required: false,
          phone: '+13165188211',
          restricted_by_admin_units: false,
          role: 'Owner',
          status: 'Active',
        },
      },
    ],
    _type: 'duo_admin',
    active: true,
    admin: true,
    adminId: 'DEUDTXS9EB88IQN84PY5',
    createdOn: undefined,
    displayName: 'Adam Pierson',
    email: 'adam.pierson@jupiterone.com',
    id: 'DEUDTXS9EB88IQN84PY5',
    lastLogin: 1645136145,
    name: 'Adam Pierson',
    passwordChangeRequired: false,
    phone: '+13165188211',
    restrictedByAdminUnits: false,
    role: 'Owner',
    status: 'active',
    username: 'adam.pierson@jupiterone.com',
  },
  {
    _class: ['UserGroup'],
    _key: 'duo-group:DGYM32D735SEKRC8X7S5',
    _rawData: [
      {
        name: 'default',
        rawData: {
          desc: 'test group',
          group_id: 'DGYM32D735SEKRC8X7S5',
          mobile_otp_enabled: false,
          name: 'testJ1Group',
          push_enabled: false,
          sms_enabled: false,
          status: 'Bypass',
        },
      },
    ],
    _type: 'duo_group',
    active: false,
    createdOn: undefined,
    desc: 'test group',
    description: 'test group',
    displayName: 'testJ1Group',
    groupId: 'DGYM32D735SEKRC8X7S5',
    id: 'DGYM32D735SEKRC8X7S5',
    mobileOtpEnabled: false,
    name: 'testJ1Group',
    pushEnabled: false,
    smsEnabled: false,
    status: 'Bypass',
  },
  {
    _class: ['User'],
    _key: 'duo-user:DUNWSZS0P50553CA4FAH',
    _rawData: [
      {
        name: 'default',
        rawData: {
          alias1: null,
          alias2: null,
          alias3: null,
          alias4: null,
          aliases: {},
          created: 1644967413,
          desktoptokens: [],
          email: 'austin.kelleher+duotest@jupiterone.com',
          firstname: null,
          groups: [
            {
              desc: 'test group',
              group_id: 'DGYM32D735SEKRC8X7S5',
              mobile_otp_enabled: false,
              name: 'testJ1Group',
              push_enabled: false,
              sms_enabled: false,
              status: 'Bypass',
            },
          ],
          is_enrolled: true,
          last_directory_sync: null,
          last_login: null,
          lastname: null,
          notes: 'Hello notes!',
          phones: [
            {
              activated: true,
              capabilities: ['auto', 'push', 'sms', 'mobile_otp'],
              encrypted: 'Encrypted',
              extension: '',
              fingerprint: 'Configured',
              last_seen: '2022-02-17T16:42:38',
              model: 'Google Pixel 5',
              name: '',
              number: '+15859430080',
              phone_id: 'DPB9DRDAI6PONK6CVHKC',
              platform: 'Google Android',
              screenlock: 'Locked',
              sms_passcodes_sent: false,
              tampered: 'Not tampered',
              type: 'Mobile',
            },
          ],
          realname: 'Austin Kelleher Test',
          status: 'active',
          tokens: [],
          u2ftokens: [],
          user_id: 'DUNWSZS0P50553CA4FAH',
          username: 'austinkellehertest',
          webauthncredentials: [],
        },
      },
    ],
    _type: 'duo_user',
    active: true,
    createdOn: 1644967413,
    displayName: 'Austin Kelleher Test',
    email: 'austin.kelleher+duotest@jupiterone.com',
    firstName: undefined,
    id: 'DUNWSZS0P50553CA4FAH',
    lastLogin: undefined,
    lastName: undefined,
    mfaEnabled: true,
    name: 'Austin Kelleher Test',
    notes: ['Hello notes!'],
    status: 'active',
    username: 'austinkellehertest',
  },
];
